name: Main Worflow Pipeline
run-name: ${{ github.actor }} Worflow Code  🚀
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  DeployBeta:
    name: Deploy to Beta
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    environment:
      name: development
      url: 'http://erbase.morea-ifs.org'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_IP }} << 'EOF'
          cd ${{ secrets.INSIDE_PROJECT_DIR }}
          git pull origin main
          date
          EOF
  DeployProd:
    name: Deploy to Beta
    if: github.event_name == 'pull_request'
    needs: [DeployBeta]
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 'http://erbase.sbc.org.br'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/VPN-Servicos.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          server-dir: public_html/gabriel/
